<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DefaultItemExcludes>$(DefaultItemExcludes);Tests/**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../ProtocolTestApplication/ProtocoleTestApp/Monero/Native/build/xtop_monero.dll"
              Link="xtop_monero.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"
              Condition="'$(OS)' == 'Windows_NT' And Exists('../ProtocolTestApplication/ProtocoleTestApp/Monero/Native/build/xtop_monero.dll')" />
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1"/>
    </ItemGroup>

</Project>
